services:
  9router:
    build:
      context: .
      dockerfile: Dockerfile
    image: 9router-local:latest
    container_name: 9router
    restart: always
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    environment:
      DATA_DIR: /app/data
      PORT: "20128"
      HOSTNAME: "0.0.0.0"
      NODE_ENV: production
      HEADROOM_URL: http://headroom:8787
    depends_on:
      - headroom
    networks:
      - 9router_network
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.9router.rule=Host(`${APP_HOST:-9router.localhost}`)
      - traefik.http.routers.9router.tls=true
      - traefik.http.routers.9router.entrypoints=websecure
      - traefik.http.routers.9router.tls.certresolver=myresolver
      - traefik.http.services.9router.loadbalancer.server.port=20128
      - traefik.docker.network=traefik

  headroom:
    image: ghcr.io/chopratejas/headroom:latest
    container_name: headroom
    restart: always
    ports:
      - "8787:8787"
    networks:
      - 9router_network

networks:
  9router_network:
    driver: bridge
  traefik:
    external: true
